# Generated by Django 6.0.1 on 2026-01-10 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(max_length=50, unique=True, verbose_name='Shipment ID')),
                ('booking_number', models.CharField(blank=True, max_length=50, verbose_name='Booking / BL')),
                ('container_number', models.CharField(blank=True, max_length=50, verbose_name='No. Contenedor/Caja')),
                ('transport_type', models.CharField(choices=[('terrestrial', 'Terrestre'), ('maritime', 'Marítimo'), ('mixed', 'Mixto')], max_length=20, verbose_name='Tipo de Transporte')),
                ('origin', models.CharField(max_length=100, verbose_name='Origen / Puerto Salida')),
                ('destination', models.CharField(max_length=100, verbose_name='Destino / Puerto Llegada')),
                ('etd', models.DateField(blank=True, null=True, verbose_name='Fecha Est. Salida (ETD)')),
                ('eta', models.DateField(blank=True, null=True, verbose_name='Fecha Est. Llegada (ETA)')),
                ('real_arrival_date', models.DateField(blank=True, null=True, verbose_name='Fecha Real Llegada')),
                ('incoterm', models.CharField(blank=True, max_length=10, verbose_name='Incoterm')),
                ('weight_sent', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Peso Enviado (KG)')),
                ('weight_received', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Peso Recibido (KG)')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_transit', 'En Tránsito'), ('delivered', 'Entregado'), ('facturated', 'Facturado'), ('closed', 'Cerrado'), ('incident', 'Con Incidencia')], default='pending', max_length=20, verbose_name='Estatus Operativo')),
                ('is_invoiced', models.BooleanField(default=False, verbose_name='Facturado')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Fecha Facturación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client', verbose_name='Cliente Asociado')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistics_orders', to='purchases.purchaseorder', verbose_name='Orden de Compra (Origen)')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable Logístico')),
            ],
            options={
                'verbose_name': 'Orden Logística',
                'verbose_name_plural': 'Órdenes Logísticas',
            },
        ),
        migrations.CreateModel(
            name='LogisticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Evento')),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Ubicación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='logistics.logisticsorder')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LogisticsDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='logistics/%Y/%m/')),
                ('doc_type', models.CharField(choices=[('invoice', 'Factura Comercial'), ('packing_list', 'Packing List'), ('pedimento', 'Pedimento Aduanal'), ('contract', 'Contrato'), ('insurance', 'Seguro'), ('photo', 'Fotografía Carga/Entrega'), ('other', 'Otro')], max_length=20, verbose_name='Tipo de Documento')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='logistics.logisticsorder')),
            ],
        ),
        migrations.CreateModel(
            name='WeightLossRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lost_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad Perdida (KG)')),
                ('reason', models.CharField(max_length=100, verbose_name='Motivo (Daño, Humedad, etc.)')),
                ('description', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loss_records', to='logistics.logisticsorder')),
            ],
        ),
    ]
