# Generated by Django 6.0.1 on 2026-01-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre / Razón Social')),
                ('tax_id', models.CharField(max_length=50, unique=True, verbose_name='RFC / Tax ID')),
                ('address', models.TextField(blank=True, verbose_name='Dirección Fiscal')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre de Contacto')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Categoría/Rubro')),
                ('credit_days', models.IntegerField(default=0, verbose_name='Días de Crédito')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['name'],
            },
        ),
    ]
