# Generated by Django 6.0.1 on 2026-01-10 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(max_length=50, unique=True, verbose_name='Folio Cotización')),
                ('date_issued', models.DateField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('valid_until', models.DateField(verbose_name='Válida hasta')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviada'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='draft', max_length=20, verbose_name='Estatus')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='clients.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Folio Venta')),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de Pago'), ('paid', 'Pagada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estatus Pago')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto Pagado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Cliente')),
                ('quotation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.quotation', verbose_name='Cotización Origen')),
            ],
            options={
                'verbose_name': 'Orden de Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.product', verbose_name='Producto')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.quotation')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesorder')),
            ],
        ),
    ]
